name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
    - name: Setting up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Unit tests
      run: |
        python -m unittest tests/test_tree.py